name: Deploy

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add environment vars from secrets
        run: |
          echo "  DB_URL1: ${{ secrets.URL1 }}" >> src/main/appengine/app.yaml
          echo "  DB_URL2: ${{ secrets.URL2 }}" >> src/main/appengine/app.yaml
          echo "  DB_URL3: ${{ secrets.URL3 }}" >> src/main/appengine/app.yaml

      - name: Check environment vars
        run: >
          cat src/main/appengine/app.yaml

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Deploy to App Engine
        run: ./gradlew appengineDeploy